casiimir/CB8-team-d

README.md

test: prova branch

---

src/components/task/Task.jsx
src/components/task/index.jsx
src/components/task/index.module.scss
src/components/taskList/TaskList.jsx
src/components/taskList/index.jsx
src/components/taskList/index.module.scss
src/pages/api/dailies/index.js
src/pages/api/todos/index.js
src/pages/dailies/index.jsx
src/pages/habits/index.jsx
src/pages/todos/index.jsx

Aggiunta pagine dailies e todos, implementati i componenti Task e TaskList.

feat: aggiunta pagine e implementati componenti

---

src/components/task/Task.jsx
src/components/taskList/TaskList.jsx
src/components/taskModal/TaskModal.jsx
src/pages/dailies/index.jsx
src/pages/habits/index.jsx
src/pages/todos/index.jsx
src/stores/context.jsx

Aggiunto bottone per cancellare task in ogni pagina (Todos, Habits, Dailies)

Delete method task

---

src/components/plot/Plot.jsx
src/components/plot/index.jsx
src/components/plot/index.module.scss
src/pages/garden/index.jsx
src/styles/Garden.module.scss

feat: FE pagina Garden bozza

---

src/components/task/Task.jsx
src/components/task/index.module.scss
src/components/taskModal/TaskModal.jsx

funzione del form della modale in tutt'e tre le pagine, comprese le date.

feat: taskModal form

---

src/components/navbar/Navbar.jsx
src/components/plot/Plot.jsx
src/components/plot/index.module.scss
src/pages/garden/index.jsx
src/styles/Garden.module.scss

Il componente navbar presenta il logo quando si trova nella pagina garden.
Prova mockGarden e mappatura del mock

fix: navbar e garden prova

---

src/assets/mixins.module.scss
src/assets/variables.module.scss
src/components/header/index.module.scss
src/components/login/index.module.scss
src/components/navbar/index.module.scss
src/components/task/index.module.scss
src/components/taskList/index.module.scss
src/components/taskModal/index.module.scss
src/styles/globals.css

Modifica stile globale, variabili, mixin.

Modifica stile

---

src/components/gardenModal/GardenModal.jsx
src/components/gardenModal/index.jsx
src/components/gardenModal/index.module.scss
src/components/plot/Plot.jsx
src/components/plot/index.module.scss
src/pages/garden/index.jsx
src/styles/Garden.module.scss

created garden shop modal

---

src/components/gardenModal/GardenModal.jsx
src/components/gardenModal/index.module.scss
src/components/navbar/Navbar.jsx
src/components/navbar/index.module.scss
src/components/taskModal/TaskModal.jsx
src/components/taskModal/index.module.scss

Navbar:
- Testi sotto le icone
- Comportamento del pulsante centrale nella pagina garden
TaskModal:
- Creazione di una nuova task all'invio da tastiera, oltre che dal bottone
- Aggiunta bottone di chiusura della modale
GardenModal:
- Aggiunta bottone di chiusura della modale
- Aggiunta bottone di conferma selezione della pianta
- Aggiunta nome della pianta

chore style and GardenModal

---

src/models/garden.js
src/models/userResources.js
src/pages/api/auth/signup.js

Aggiunta la creazione del garden e delle risorse utente.

feat: creazione user, userResources e garden

---

src/components/gardenModal/GardenModal.jsx
src/components/taskModal/TaskModal.jsx
src/models/garden.js
src/pages/api/dailies/index.js
src/pages/garden/index.jsx

Fetch API garden
Focus input modal

fetch API Garden

---

src/components/gardenModal/GardenModal.jsx
src/components/plot/Plot.jsx
src/pages/api/garden/[id].js
src/pages/garden/index.jsx

GardenModal fetch moved in parent component, error fixed in api call, treesName added in garden

fix/gardenModal fetch moved in parentComponent

---

src/assets/mixins.module.scss
src/assets/variables.module.scss
src/components/header/index.module.scss
src/components/navbar/index.module.scss
src/components/task/index.module.scss
src/components/taskList/index.module.scss
src/pages/userpage/index.jsx
src/styles/globals.css
src/styles/userpage.module.scss

Fix vari su css e aggiunta pagina userpage

fix stili e add userpage

---

src/components/plot/Plot.jsx
src/pages/garden/index.jsx

Aggiunta feat di rimozione dell'albero.
Se l'utente clicca su un plot occupato da un albero, si aprono due bottoni, uno rimuove l'albero e l'altro cancella l'azione.

feat: rimozione albero

---

src/components/loader/Loader.jsx
src/components/loader/index.jsx
src/components/loader/index.module.scss
src/pages/dailies/index.jsx
src/pages/garden/index.jsx
src/pages/habits/index.jsx
src/pages/index.jsx
src/pages/todos/index.jsx

Aggiunto loader alle 4 pagine principali

feat: loader

---

public/trees.json
src/components/plot/Plot.jsx
src/components/plot/index.module.scss
src/components/taskModal/index.module.scss

Aggiunti buttons per rimozione alberi

Garden buttons

---

src/components/header/Header.jsx
src/components/task/Task.jsx

ho cambiato l'ordine delle risorse nell'header e le task corrispondenti per riflettere il colore

header resources order

---

src/assets/mixins.module.scss
src/components/gardenModal/index.module.scss
src/components/header/index.module.scss
src/components/task/Task.jsx
src/components/task/index.module.scss
src/components/taskList/index.module.scss
src/pages/userpage/index.jsx
src/styles/globals.css
src/styles/lists.module.scss
src/styles/userpage.module.scss

fix userpage and css tasklist

---

src/components/plot/Plot.jsx
src/pages/404.jsx
src/pages/dailies/index.jsx
src/pages/garden/index.jsx
src/pages/habits/index.jsx
src/pages/login/index.jsx
src/pages/signup/index.jsx
src/pages/todos/index.jsx

Nomi degli stili tutti in minuscolo, import modificato di conseguenza.

fix: nomi degli stili omologati, modifice agli import

---

src/pages/login/index.jsx
src/pages/signup/index.jsx

Aggiunti messaggi di alert nella pagina login e signup.

feat: aggiunti messaggi di alert in login e signup

---

src/components/task/Task.jsx
src/models/daily.js

Aggiunta funzionalita' condizionale per la renderizzaqzione del LastCompleted nelle task.

fix: lastCompleted in Task

---

src/pages/api/auth/[...nextauth].js
src/pages/todos/index.jsx
src/pages/userpage/index.jsx

Aggiunta funzionalita' logout user in userpage e loader in todopage.

feat: logout utente, modifiche a TodoPage

---

src/pages/userpage/index.jsx

Aggiunto redirect al /login quando si clicca il button logOut

feat: funzione di redirecting a /login con il logout

---

src/styles/login.module.scss

aggiunto no-wrap al login wrapper

nowrap a signup_wrapper

---

src/pages/login/index.jsx
src/pages/userpage/index.jsx

Aggiunto lo useSession al Login, il push a /garden avviene solo se la sessione risulta autenticata.

fix: nuova logica login

---

src/components/plot/Plot.jsx
src/components/plot/index.module.scss
src/components/task/index.module.scss
src/components/taskList/TaskList.jsx

Animazioni framer motion in TaskList e Plot

animazioni task e alberi
